frontend:
  image: "myregistry/frontend:stable"
  replicas: 3
  service:
    type: LoadBalancer
    port: 80

backend:
  image: "myregistry/backend:stable"
  replicas: 3
  service:
    type: ClusterIP
    port: 8080

database:
  image: "myregistry/postgres:13"
  replicas: 2
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    storageClass: "fast-ssd"
    accessMode: ReadWriteOnce
    size: 50Gi
