frontend:
  image: 
    repository: "myregistry/backend"
    tag: "latest"
  replicas: 1
  service:
    type: ClusterIP
    port: 80

backend:
  image: "myregistry/backend:latest"
  replicas: 1
  service:
    type: ClusterIP
    port: 8080

database:
  image: "myregistry/postgres:13"
  replicas: 1
  service:
    type: ClusterIP
    port: 5432
  persistence:
    enabled: true
    storageClass: "standard"
    accessMode: ReadWriteOnce
    size: 8Gi
