apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-database
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
  selector:
    app: {{ include "my-app.name" . }}
    component: database
